name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout respository
        uses: actions/checkout@v3

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: meilii
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 🛠️ Build and tag Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: 🐳 Tag & Push Backend image
        run: |
          docker tag todo101-todo-backend meilii/todo-backend:latest
          docker push meilii/todo-backend:latest

      - name: 🐳 Tag & Push Front image
        run: |
          docker tag todo101-todo-frontend meilii/todo-frontend:latest
          docker push meilii/todo-frontend:latest
